try to set related company approach but we have
KeyError: 'Field company_id referenced in related field definition
l10n_latam.payment.mass.transfer.company_id does not exist.'